/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as HelpRouteImport } from './routes/help'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SpeakUpRouteImport } from './routes/speak-up'
import { Route as AttendanceIndexRouteImport } from './routes/attendance.index'
import { Route as AttendanceIdRouteImport } from './routes/attendance.$id'
import { Route as AttendanceClockRouteImport } from './routes/attendance.clock'
import { Route as AttendanceNewRouteImport } from './routes/attendance.new'
import { Route as ConfigurationIndexRouteImport } from './routes/configuration.index'
import { Route as ConfigurationBusinessRouteImport } from './routes/configuration.business'
import { Route as ConfigurationComplianceRouteImport } from './routes/configuration.compliance'
import { Route as ConfigurationOrganisationRouteImport } from './routes/configuration.organisation'
import { Route as ConfigurationProcessRouteImport } from './routes/configuration.process'
import { Route as ConfigurationRolesRouteImport } from './routes/configuration.roles'
import { Route as ConfigurationTechnicalRouteImport } from './routes/configuration.technical'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as EmployeesNewRouteImport } from './routes/employees.new'
import { Route as ExperienceAnnouncementsRouteImport } from './routes/experience.announcements'
import { Route as ExperienceKnowledgeRouteImport } from './routes/experience.knowledge'
import { Route as ExperienceLettersRouteImport } from './routes/experience.letters'
import { Route as LeaveIndexRouteImport } from './routes/leave.index'
import { Route as LeaveIdRouteImport } from './routes/leave.$id'
import { Route as LeaveNewRouteImport } from './routes/leave.new'
import { Route as LifecycleIndexRouteImport } from './routes/lifecycle.index'
import { Route as LifecycleAlumniRouteImport } from './routes/lifecycle.alumni'
import { Route as LifecycleAssetsRouteImport } from './routes/lifecycle.assets'
import { Route as LifecycleJourneysRouteImport } from './routes/lifecycle.journeys'
import { Route as LifecycleMobilityRouteImport } from './routes/lifecycle.mobility'
import { Route as LifecycleMovementsRouteImport } from './routes/lifecycle.movements'
import { Route as LifecycleOffboardingRouteImport } from './routes/lifecycle.offboarding'
import { Route as LifecycleOnboardingRouteImport } from './routes/lifecycle.onboarding'
import { Route as PayCompensationRouteImport } from './routes/pay.compensation'
import { Route as PayrollIndexRouteImport } from './routes/payroll.index'
import { Route as PayrollExceptionsRouteImport } from './routes/payroll.exceptions'
import { Route as PayrollRunsRouteImport } from './routes/payroll.runs'
import { Route as PayslipsIndexRouteImport } from './routes/payslips.index'
import { Route as PayslipsIdRouteImport } from './routes/payslips.$id'
import { Route as PeopleDataQualityRouteImport } from './routes/people.data-quality'
import { Route as PeopleDocumentsRouteImport } from './routes/people.documents'
import { Route as PeopleOrgRouteImport } from './routes/people.org'
import { Route as PeoplePositionsRouteImport } from './routes/people.positions'
import { Route as PeoplePrivacyRouteImport } from './routes/people.privacy'
import { Route as RecruitmentIndexRouteImport } from './routes/recruitment.index'
import { Route as RecruitmentCandidatesRouteImport } from './routes/recruitment.candidates'
import { Route as RecruitmentOffersRouteImport } from './routes/recruitment.offers'
import { Route as RecruitmentRequisitionsRouteImport } from './routes/recruitment.requisitions'
import { Route as RecruitmentVacanciesRouteImport } from './routes/recruitment.vacancies'
import { Route as RelationsIndexRouteImport } from './routes/relations.index'
import { Route as RelationsCasesRouteImport } from './routes/relations.cases'
import { Route as RelationsDisciplineRouteImport } from './routes/relations.discipline'
import { Route as RelationsEthicsRouteImport } from './routes/relations.ethics'
import { Route as RelationsLabourRouteImport } from './routes/relations.labour'
import { Route as RelationsSafetyRouteImport } from './routes/relations.safety'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsBuilderRouteImport } from './routes/reports.builder'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as TalentFeedbackRouteImport } from './routes/talent.feedback'
import { Route as TalentGoalsRouteImport } from './routes/talent.goals'
import { Route as TalentLearningRouteImport } from './routes/talent.learning'
import { Route as TalentReviewsRouteImport } from './routes/talent.reviews'
import { Route as TalentSuccessionRouteImport } from './routes/talent.succession'
import { Route as TimeSchedulesRouteImport } from './routes/time.schedules'
import { Route as TimeTimesheetsRouteImport } from './routes/time.timesheets'
import { Route as TimeToilRouteImport } from './routes/time.toil'
import { Route as TimeTravelRouteImport } from './routes/time.travel'
import { Route as TimeUtilisationRouteImport } from './routes/time.utilisation'
import { Route as EmployeesIdEditRouteImport } from './routes/employees.$id.edit'
import { Route as LifecycleMovementsNewRouteImport } from './routes/lifecycle.movements.new'
import { Route as LifecycleOffboardingIdRouteImport } from './routes/lifecycle.offboarding.$id'
import { Route as LifecycleOnboardingIdRouteImport } from './routes/lifecycle.onboarding.$id'
import { Route as PayrollRunsIdRouteImport } from './routes/payroll.runs.$id'
import { Route as PayrollRunsNewRouteImport } from './routes/payroll.runs.new'
import { Route as PeoplePositionsIdRouteImport } from './routes/people.positions.$id'
import { Route as RecruitmentCandidatesIdRouteImport } from './routes/recruitment.candidates.$id'
import { Route as RecruitmentRequisitionsNewRouteImport } from './routes/recruitment.requisitions.new'
import { Route as RelationsCasesIdRouteImport } from './routes/relations.cases.$id'
import { Route as TalentReviewsIdRouteImport } from './routes/talent.reviews.$id'
import { Route as TimeExpensesIndexRouteImport } from './routes/time.expenses.index'
import { Route as TimeExpensesNewRouteImport } from './routes/time.expenses.new'
import { Route as PayrollRunsIdEditRouteImport } from './routes/payroll.runs.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakUpRoute = SpeakUpRouteImport.update({
  id: '/speak-up',
  path: '/speak-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIdRoute = AttendanceIdRouteImport.update({
  id: '/attendance/$id',
  path: '/attendance/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceClockRoute = AttendanceClockRouteImport.update({
  id: '/attendance/clock',
  path: '/attendance/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceNewRoute = AttendanceNewRouteImport.update({
  id: '/attendance/new',
  path: '/attendance/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationIndexRoute = ConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationBusinessRoute = ConfigurationBusinessRouteImport.update({
  id: '/configuration/business',
  path: '/configuration/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationComplianceRoute = ConfigurationComplianceRouteImport.update({
  id: '/configuration/compliance',
  path: '/configuration/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationOrganisationRoute =
  ConfigurationOrganisationRouteImport.update({
    id: '/configuration/organisation',
    path: '/configuration/organisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfigurationProcessRoute = ConfigurationProcessRouteImport.update({
  id: '/configuration/process',
  path: '/configuration/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRolesRoute = ConfigurationRolesRouteImport.update({
  id: '/configuration/roles',
  path: '/configuration/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationTechnicalRoute = ConfigurationTechnicalRouteImport.update({
  id: '/configuration/technical',
  path: '/configuration/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceAnnouncementsRoute = ExperienceAnnouncementsRouteImport.update({
  id: '/experience/announcements',
  path: '/experience/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceKnowledgeRoute = ExperienceKnowledgeRouteImport.update({
  id: '/experience/knowledge',
  path: '/experience/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceLettersRoute = ExperienceLettersRouteImport.update({
  id: '/experience/letters',
  path: '/experience/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveIndexRoute = LeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveIdRoute = LeaveIdRouteImport.update({
  id: '/leave/$id',
  path: '/leave/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveNewRoute = LeaveNewRouteImport.update({
  id: '/leave/new',
  path: '/leave/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleIndexRoute = LifecycleIndexRouteImport.update({
  id: '/lifecycle/',
  path: '/lifecycle/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleAlumniRoute = LifecycleAlumniRouteImport.update({
  id: '/lifecycle/alumni',
  path: '/lifecycle/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleAssetsRoute = LifecycleAssetsRouteImport.update({
  id: '/lifecycle/assets',
  path: '/lifecycle/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleJourneysRoute = LifecycleJourneysRouteImport.update({
  id: '/lifecycle/journeys',
  path: '/lifecycle/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleMobilityRoute = LifecycleMobilityRouteImport.update({
  id: '/lifecycle/mobility',
  path: '/lifecycle/mobility',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleMovementsRoute = LifecycleMovementsRouteImport.update({
  id: '/lifecycle/movements',
  path: '/lifecycle/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleOffboardingRoute = LifecycleOffboardingRouteImport.update({
  id: '/lifecycle/offboarding',
  path: '/lifecycle/offboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleOnboardingRoute = LifecycleOnboardingRouteImport.update({
  id: '/lifecycle/onboarding',
  path: '/lifecycle/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCompensationRoute = PayCompensationRouteImport.update({
  id: '/pay/compensation',
  path: '/pay/compensation',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollExceptionsRoute = PayrollExceptionsRouteImport.update({
  id: '/payroll/exceptions',
  path: '/payroll/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRunsRoute = PayrollRunsRouteImport.update({
  id: '/payroll/runs',
  path: '/payroll/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PayslipsIndexRoute = PayslipsIndexRouteImport.update({
  id: '/payslips/',
  path: '/payslips/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayslipsIdRoute = PayslipsIdRouteImport.update({
  id: '/payslips/$id',
  path: '/payslips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleDataQualityRoute = PeopleDataQualityRouteImport.update({
  id: '/people/data-quality',
  path: '/people/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleDocumentsRoute = PeopleDocumentsRouteImport.update({
  id: '/people/documents',
  path: '/people/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleOrgRoute = PeopleOrgRouteImport.update({
  id: '/people/org',
  path: '/people/org',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePositionsRoute = PeoplePositionsRouteImport.update({
  id: '/people/positions',
  path: '/people/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePrivacyRoute = PeoplePrivacyRouteImport.update({
  id: '/people/privacy',
  path: '/people/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentIndexRoute = RecruitmentIndexRouteImport.update({
  id: '/recruitment/',
  path: '/recruitment/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentCandidatesRoute = RecruitmentCandidatesRouteImport.update({
  id: '/recruitment/candidates',
  path: '/recruitment/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentOffersRoute = RecruitmentOffersRouteImport.update({
  id: '/recruitment/offers',
  path: '/recruitment/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRequisitionsRoute = RecruitmentRequisitionsRouteImport.update({
  id: '/recruitment/requisitions',
  path: '/recruitment/requisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentVacanciesRoute = RecruitmentVacanciesRouteImport.update({
  id: '/recruitment/vacancies',
  path: '/recruitment/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsIndexRoute = RelationsIndexRouteImport.update({
  id: '/relations/',
  path: '/relations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsCasesRoute = RelationsCasesRouteImport.update({
  id: '/relations/cases',
  path: '/relations/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsDisciplineRoute = RelationsDisciplineRouteImport.update({
  id: '/relations/discipline',
  path: '/relations/discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsEthicsRoute = RelationsEthicsRouteImport.update({
  id: '/relations/ethics',
  path: '/relations/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsLabourRoute = RelationsLabourRouteImport.update({
  id: '/relations/labour',
  path: '/relations/labour',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsSafetyRoute = RelationsSafetyRouteImport.update({
  id: '/relations/safety',
  path: '/relations/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsBuilderRoute = ReportsBuilderRouteImport.update({
  id: '/reports/builder',
  path: '/reports/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentFeedbackRoute = TalentFeedbackRouteImport.update({
  id: '/talent/feedback',
  path: '/talent/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentGoalsRoute = TalentGoalsRouteImport.update({
  id: '/talent/goals',
  path: '/talent/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentLearningRoute = TalentLearningRouteImport.update({
  id: '/talent/learning',
  path: '/talent/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentReviewsRoute = TalentReviewsRouteImport.update({
  id: '/talent/reviews',
  path: '/talent/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentSuccessionRoute = TalentSuccessionRouteImport.update({
  id: '/talent/succession',
  path: '/talent/succession',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeSchedulesRoute = TimeSchedulesRouteImport.update({
  id: '/time/schedules',
  path: '/time/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTimesheetsRoute = TimeTimesheetsRouteImport.update({
  id: '/time/timesheets',
  path: '/time/timesheets',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeToilRoute = TimeToilRouteImport.update({
  id: '/time/toil',
  path: '/time/toil',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTravelRoute = TimeTravelRouteImport.update({
  id: '/time/travel',
  path: '/time/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeUtilisationRoute = TimeUtilisationRouteImport.update({
  id: '/time/utilisation',
  path: '/time/utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdEditRoute = EmployeesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EmployeesIdRoute,
} as any)
const LifecycleMovementsNewRoute = LifecycleMovementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LifecycleMovementsRoute,
} as any)
const LifecycleOffboardingIdRoute = LifecycleOffboardingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LifecycleOffboardingRoute,
} as any)
const LifecycleOnboardingIdRoute = LifecycleOnboardingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LifecycleOnboardingRoute,
} as any)
const PayrollRunsIdRoute = PayrollRunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PayrollRunsRoute,
} as any)
const PayrollRunsNewRoute = PayrollRunsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PayrollRunsRoute,
} as any)
const PeoplePositionsIdRoute = PeoplePositionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeoplePositionsRoute,
} as any)
const RecruitmentCandidatesIdRoute = RecruitmentCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecruitmentCandidatesRoute,
} as any)
const RecruitmentRequisitionsNewRoute =
  RecruitmentRequisitionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => RecruitmentRequisitionsRoute,
  } as any)
const RelationsCasesIdRoute = RelationsCasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RelationsCasesRoute,
} as any)
const TalentReviewsIdRoute = TalentReviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TalentReviewsRoute,
} as any)
const TimeExpensesIndexRoute = TimeExpensesIndexRouteImport.update({
  id: '/time/expenses/',
  path: '/time/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeExpensesNewRoute = TimeExpensesNewRouteImport.update({
  id: '/time/expenses/new',
  path: '/time/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRunsIdEditRoute = PayrollRunsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PayrollRunsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/help': typeof HelpRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/speak-up': typeof SpeakUpRoute
  '/attendance/$id': typeof AttendanceIdRoute
  '/attendance/clock': typeof AttendanceClockRoute
  '/attendance/new': typeof AttendanceNewRoute
  '/configuration/business': typeof ConfigurationBusinessRoute
  '/configuration/compliance': typeof ConfigurationComplianceRoute
  '/configuration/organisation': typeof ConfigurationOrganisationRoute
  '/configuration/process': typeof ConfigurationProcessRoute
  '/configuration/roles': typeof ConfigurationRolesRoute
  '/configuration/technical': typeof ConfigurationTechnicalRoute
  '/employees/$id': typeof EmployeesIdRouteWithChildren
  '/employees/new': typeof EmployeesNewRoute
  '/experience/announcements': typeof ExperienceAnnouncementsRoute
  '/experience/knowledge': typeof ExperienceKnowledgeRoute
  '/experience/letters': typeof ExperienceLettersRoute
  '/leave/$id': typeof LeaveIdRoute
  '/leave/new': typeof LeaveNewRoute
  '/lifecycle/alumni': typeof LifecycleAlumniRoute
  '/lifecycle/assets': typeof LifecycleAssetsRoute
  '/lifecycle/journeys': typeof LifecycleJourneysRoute
  '/lifecycle/mobility': typeof LifecycleMobilityRoute
  '/lifecycle/movements': typeof LifecycleMovementsRouteWithChildren
  '/lifecycle/offboarding': typeof LifecycleOffboardingRouteWithChildren
  '/lifecycle/onboarding': typeof LifecycleOnboardingRouteWithChildren
  '/pay/compensation': typeof PayCompensationRoute
  '/payroll/exceptions': typeof PayrollExceptionsRoute
  '/payroll/runs': typeof PayrollRunsRouteWithChildren
  '/payslips/$id': typeof PayslipsIdRoute
  '/people/data-quality': typeof PeopleDataQualityRoute
  '/people/documents': typeof PeopleDocumentsRoute
  '/people/org': typeof PeopleOrgRoute
  '/people/positions': typeof PeoplePositionsRouteWithChildren
  '/people/privacy': typeof PeoplePrivacyRoute
  '/recruitment/candidates': typeof RecruitmentCandidatesRouteWithChildren
  '/recruitment/offers': typeof RecruitmentOffersRoute
  '/recruitment/requisitions': typeof RecruitmentRequisitionsRouteWithChildren
  '/recruitment/vacancies': typeof RecruitmentVacanciesRoute
  '/relations/cases': typeof RelationsCasesRouteWithChildren
  '/relations/discipline': typeof RelationsDisciplineRoute
  '/relations/ethics': typeof RelationsEthicsRoute
  '/relations/labour': typeof RelationsLabourRoute
  '/relations/safety': typeof RelationsSafetyRoute
  '/reports/builder': typeof ReportsBuilderRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/talent/feedback': typeof TalentFeedbackRoute
  '/talent/goals': typeof TalentGoalsRoute
  '/talent/learning': typeof TalentLearningRoute
  '/talent/reviews': typeof TalentReviewsRouteWithChildren
  '/talent/succession': typeof TalentSuccessionRoute
  '/time/schedules': typeof TimeSchedulesRoute
  '/time/timesheets': typeof TimeTimesheetsRoute
  '/time/toil': typeof TimeToilRoute
  '/time/travel': typeof TimeTravelRoute
  '/time/utilisation': typeof TimeUtilisationRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/configuration/': typeof ConfigurationIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/lifecycle/': typeof LifecycleIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/payslips/': typeof PayslipsIndexRoute
  '/recruitment/': typeof RecruitmentIndexRoute
  '/relations/': typeof RelationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/employees/$id/edit': typeof EmployeesIdEditRoute
  '/lifecycle/movements/new': typeof LifecycleMovementsNewRoute
  '/lifecycle/offboarding/$id': typeof LifecycleOffboardingIdRoute
  '/lifecycle/onboarding/$id': typeof LifecycleOnboardingIdRoute
  '/payroll/runs/$id': typeof PayrollRunsIdRouteWithChildren
  '/payroll/runs/new': typeof PayrollRunsNewRoute
  '/people/positions/$id': typeof PeoplePositionsIdRoute
  '/recruitment/candidates/$id': typeof RecruitmentCandidatesIdRoute
  '/recruitment/requisitions/new': typeof RecruitmentRequisitionsNewRoute
  '/relations/cases/$id': typeof RelationsCasesIdRoute
  '/talent/reviews/$id': typeof TalentReviewsIdRoute
  '/time/expenses/new': typeof TimeExpensesNewRoute
  '/time/expenses/': typeof TimeExpensesIndexRoute
  '/payroll/runs/$id/edit': typeof PayrollRunsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/help': typeof HelpRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/speak-up': typeof SpeakUpRoute
  '/attendance/$id': typeof AttendanceIdRoute
  '/attendance/clock': typeof AttendanceClockRoute
  '/attendance/new': typeof AttendanceNewRoute
  '/configuration/business': typeof ConfigurationBusinessRoute
  '/configuration/compliance': typeof ConfigurationComplianceRoute
  '/configuration/organisation': typeof ConfigurationOrganisationRoute
  '/configuration/process': typeof ConfigurationProcessRoute
  '/configuration/roles': typeof ConfigurationRolesRoute
  '/configuration/technical': typeof ConfigurationTechnicalRoute
  '/employees/$id': typeof EmployeesIdRouteWithChildren
  '/employees/new': typeof EmployeesNewRoute
  '/experience/announcements': typeof ExperienceAnnouncementsRoute
  '/experience/knowledge': typeof ExperienceKnowledgeRoute
  '/experience/letters': typeof ExperienceLettersRoute
  '/leave/$id': typeof LeaveIdRoute
  '/leave/new': typeof LeaveNewRoute
  '/lifecycle/alumni': typeof LifecycleAlumniRoute
  '/lifecycle/assets': typeof LifecycleAssetsRoute
  '/lifecycle/journeys': typeof LifecycleJourneysRoute
  '/lifecycle/mobility': typeof LifecycleMobilityRoute
  '/lifecycle/movements': typeof LifecycleMovementsRouteWithChildren
  '/lifecycle/offboarding': typeof LifecycleOffboardingRouteWithChildren
  '/lifecycle/onboarding': typeof LifecycleOnboardingRouteWithChildren
  '/pay/compensation': typeof PayCompensationRoute
  '/payroll/exceptions': typeof PayrollExceptionsRoute
  '/payroll/runs': typeof PayrollRunsRouteWithChildren
  '/payslips/$id': typeof PayslipsIdRoute
  '/people/data-quality': typeof PeopleDataQualityRoute
  '/people/documents': typeof PeopleDocumentsRoute
  '/people/org': typeof PeopleOrgRoute
  '/people/positions': typeof PeoplePositionsRouteWithChildren
  '/people/privacy': typeof PeoplePrivacyRoute
  '/recruitment/candidates': typeof RecruitmentCandidatesRouteWithChildren
  '/recruitment/offers': typeof RecruitmentOffersRoute
  '/recruitment/requisitions': typeof RecruitmentRequisitionsRouteWithChildren
  '/recruitment/vacancies': typeof RecruitmentVacanciesRoute
  '/relations/cases': typeof RelationsCasesRouteWithChildren
  '/relations/discipline': typeof RelationsDisciplineRoute
  '/relations/ethics': typeof RelationsEthicsRoute
  '/relations/labour': typeof RelationsLabourRoute
  '/relations/safety': typeof RelationsSafetyRoute
  '/reports/builder': typeof ReportsBuilderRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/talent/feedback': typeof TalentFeedbackRoute
  '/talent/goals': typeof TalentGoalsRoute
  '/talent/learning': typeof TalentLearningRoute
  '/talent/reviews': typeof TalentReviewsRouteWithChildren
  '/talent/succession': typeof TalentSuccessionRoute
  '/time/schedules': typeof TimeSchedulesRoute
  '/time/timesheets': typeof TimeTimesheetsRoute
  '/time/toil': typeof TimeToilRoute
  '/time/travel': typeof TimeTravelRoute
  '/time/utilisation': typeof TimeUtilisationRoute
  '/attendance': typeof AttendanceIndexRoute
  '/configuration': typeof ConfigurationIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/leave': typeof LeaveIndexRoute
  '/lifecycle': typeof LifecycleIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/payslips': typeof PayslipsIndexRoute
  '/recruitment': typeof RecruitmentIndexRoute
  '/relations': typeof RelationsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/talent': typeof TalentIndexRoute
  '/employees/$id/edit': typeof EmployeesIdEditRoute
  '/lifecycle/movements/new': typeof LifecycleMovementsNewRoute
  '/lifecycle/offboarding/$id': typeof LifecycleOffboardingIdRoute
  '/lifecycle/onboarding/$id': typeof LifecycleOnboardingIdRoute
  '/payroll/runs/$id': typeof PayrollRunsIdRouteWithChildren
  '/payroll/runs/new': typeof PayrollRunsNewRoute
  '/people/positions/$id': typeof PeoplePositionsIdRoute
  '/recruitment/candidates/$id': typeof RecruitmentCandidatesIdRoute
  '/recruitment/requisitions/new': typeof RecruitmentRequisitionsNewRoute
  '/relations/cases/$id': typeof RelationsCasesIdRoute
  '/talent/reviews/$id': typeof TalentReviewsIdRoute
  '/time/expenses/new': typeof TimeExpensesNewRoute
  '/time/expenses': typeof TimeExpensesIndexRoute
  '/payroll/runs/$id/edit': typeof PayrollRunsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/help': typeof HelpRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/speak-up': typeof SpeakUpRoute
  '/attendance/$id': typeof AttendanceIdRoute
  '/attendance/clock': typeof AttendanceClockRoute
  '/attendance/new': typeof AttendanceNewRoute
  '/configuration/business': typeof ConfigurationBusinessRoute
  '/configuration/compliance': typeof ConfigurationComplianceRoute
  '/configuration/organisation': typeof ConfigurationOrganisationRoute
  '/configuration/process': typeof ConfigurationProcessRoute
  '/configuration/roles': typeof ConfigurationRolesRoute
  '/configuration/technical': typeof ConfigurationTechnicalRoute
  '/employees/$id': typeof EmployeesIdRouteWithChildren
  '/employees/new': typeof EmployeesNewRoute
  '/experience/announcements': typeof ExperienceAnnouncementsRoute
  '/experience/knowledge': typeof ExperienceKnowledgeRoute
  '/experience/letters': typeof ExperienceLettersRoute
  '/leave/$id': typeof LeaveIdRoute
  '/leave/new': typeof LeaveNewRoute
  '/lifecycle/alumni': typeof LifecycleAlumniRoute
  '/lifecycle/assets': typeof LifecycleAssetsRoute
  '/lifecycle/journeys': typeof LifecycleJourneysRoute
  '/lifecycle/mobility': typeof LifecycleMobilityRoute
  '/lifecycle/movements': typeof LifecycleMovementsRouteWithChildren
  '/lifecycle/offboarding': typeof LifecycleOffboardingRouteWithChildren
  '/lifecycle/onboarding': typeof LifecycleOnboardingRouteWithChildren
  '/pay/compensation': typeof PayCompensationRoute
  '/payroll/exceptions': typeof PayrollExceptionsRoute
  '/payroll/runs': typeof PayrollRunsRouteWithChildren
  '/payslips/$id': typeof PayslipsIdRoute
  '/people/data-quality': typeof PeopleDataQualityRoute
  '/people/documents': typeof PeopleDocumentsRoute
  '/people/org': typeof PeopleOrgRoute
  '/people/positions': typeof PeoplePositionsRouteWithChildren
  '/people/privacy': typeof PeoplePrivacyRoute
  '/recruitment/candidates': typeof RecruitmentCandidatesRouteWithChildren
  '/recruitment/offers': typeof RecruitmentOffersRoute
  '/recruitment/requisitions': typeof RecruitmentRequisitionsRouteWithChildren
  '/recruitment/vacancies': typeof RecruitmentVacanciesRoute
  '/relations/cases': typeof RelationsCasesRouteWithChildren
  '/relations/discipline': typeof RelationsDisciplineRoute
  '/relations/ethics': typeof RelationsEthicsRoute
  '/relations/labour': typeof RelationsLabourRoute
  '/relations/safety': typeof RelationsSafetyRoute
  '/reports/builder': typeof ReportsBuilderRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/talent/feedback': typeof TalentFeedbackRoute
  '/talent/goals': typeof TalentGoalsRoute
  '/talent/learning': typeof TalentLearningRoute
  '/talent/reviews': typeof TalentReviewsRouteWithChildren
  '/talent/succession': typeof TalentSuccessionRoute
  '/time/schedules': typeof TimeSchedulesRoute
  '/time/timesheets': typeof TimeTimesheetsRoute
  '/time/toil': typeof TimeToilRoute
  '/time/travel': typeof TimeTravelRoute
  '/time/utilisation': typeof TimeUtilisationRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/configuration/': typeof ConfigurationIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/lifecycle/': typeof LifecycleIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/payslips/': typeof PayslipsIndexRoute
  '/recruitment/': typeof RecruitmentIndexRoute
  '/relations/': typeof RelationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/employees/$id/edit': typeof EmployeesIdEditRoute
  '/lifecycle/movements/new': typeof LifecycleMovementsNewRoute
  '/lifecycle/offboarding/$id': typeof LifecycleOffboardingIdRoute
  '/lifecycle/onboarding/$id': typeof LifecycleOnboardingIdRoute
  '/payroll/runs/$id': typeof PayrollRunsIdRouteWithChildren
  '/payroll/runs/new': typeof PayrollRunsNewRoute
  '/people/positions/$id': typeof PeoplePositionsIdRoute
  '/recruitment/candidates/$id': typeof RecruitmentCandidatesIdRoute
  '/recruitment/requisitions/new': typeof RecruitmentRequisitionsNewRoute
  '/relations/cases/$id': typeof RelationsCasesIdRoute
  '/talent/reviews/$id': typeof TalentReviewsIdRoute
  '/time/expenses/new': typeof TimeExpensesNewRoute
  '/time/expenses/': typeof TimeExpensesIndexRoute
  '/payroll/runs/$id/edit': typeof PayrollRunsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/help'
    | '/setup'
    | '/sign-in'
    | '/speak-up'
    | '/attendance/$id'
    | '/attendance/clock'
    | '/attendance/new'
    | '/configuration/business'
    | '/configuration/compliance'
    | '/configuration/organisation'
    | '/configuration/process'
    | '/configuration/roles'
    | '/configuration/technical'
    | '/employees/$id'
    | '/employees/new'
    | '/experience/announcements'
    | '/experience/knowledge'
    | '/experience/letters'
    | '/leave/$id'
    | '/leave/new'
    | '/lifecycle/alumni'
    | '/lifecycle/assets'
    | '/lifecycle/journeys'
    | '/lifecycle/mobility'
    | '/lifecycle/movements'
    | '/lifecycle/offboarding'
    | '/lifecycle/onboarding'
    | '/pay/compensation'
    | '/payroll/exceptions'
    | '/payroll/runs'
    | '/payslips/$id'
    | '/people/data-quality'
    | '/people/documents'
    | '/people/org'
    | '/people/positions'
    | '/people/privacy'
    | '/recruitment/candidates'
    | '/recruitment/offers'
    | '/recruitment/requisitions'
    | '/recruitment/vacancies'
    | '/relations/cases'
    | '/relations/discipline'
    | '/relations/ethics'
    | '/relations/labour'
    | '/relations/safety'
    | '/reports/builder'
    | '/requests/$id'
    | '/requests/new'
    | '/talent/feedback'
    | '/talent/goals'
    | '/talent/learning'
    | '/talent/reviews'
    | '/talent/succession'
    | '/time/schedules'
    | '/time/timesheets'
    | '/time/toil'
    | '/time/travel'
    | '/time/utilisation'
    | '/attendance/'
    | '/configuration/'
    | '/employees/'
    | '/leave/'
    | '/lifecycle/'
    | '/payroll/'
    | '/payslips/'
    | '/recruitment/'
    | '/relations/'
    | '/reports/'
    | '/requests/'
    | '/talent/'
    | '/employees/$id/edit'
    | '/lifecycle/movements/new'
    | '/lifecycle/offboarding/$id'
    | '/lifecycle/onboarding/$id'
    | '/payroll/runs/$id'
    | '/payroll/runs/new'
    | '/people/positions/$id'
    | '/recruitment/candidates/$id'
    | '/recruitment/requisitions/new'
    | '/relations/cases/$id'
    | '/talent/reviews/$id'
    | '/time/expenses/new'
    | '/time/expenses/'
    | '/payroll/runs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/help'
    | '/setup'
    | '/sign-in'
    | '/speak-up'
    | '/attendance/$id'
    | '/attendance/clock'
    | '/attendance/new'
    | '/configuration/business'
    | '/configuration/compliance'
    | '/configuration/organisation'
    | '/configuration/process'
    | '/configuration/roles'
    | '/configuration/technical'
    | '/employees/$id'
    | '/employees/new'
    | '/experience/announcements'
    | '/experience/knowledge'
    | '/experience/letters'
    | '/leave/$id'
    | '/leave/new'
    | '/lifecycle/alumni'
    | '/lifecycle/assets'
    | '/lifecycle/journeys'
    | '/lifecycle/mobility'
    | '/lifecycle/movements'
    | '/lifecycle/offboarding'
    | '/lifecycle/onboarding'
    | '/pay/compensation'
    | '/payroll/exceptions'
    | '/payroll/runs'
    | '/payslips/$id'
    | '/people/data-quality'
    | '/people/documents'
    | '/people/org'
    | '/people/positions'
    | '/people/privacy'
    | '/recruitment/candidates'
    | '/recruitment/offers'
    | '/recruitment/requisitions'
    | '/recruitment/vacancies'
    | '/relations/cases'
    | '/relations/discipline'
    | '/relations/ethics'
    | '/relations/labour'
    | '/relations/safety'
    | '/reports/builder'
    | '/requests/$id'
    | '/requests/new'
    | '/talent/feedback'
    | '/talent/goals'
    | '/talent/learning'
    | '/talent/reviews'
    | '/talent/succession'
    | '/time/schedules'
    | '/time/timesheets'
    | '/time/toil'
    | '/time/travel'
    | '/time/utilisation'
    | '/attendance'
    | '/configuration'
    | '/employees'
    | '/leave'
    | '/lifecycle'
    | '/payroll'
    | '/payslips'
    | '/recruitment'
    | '/relations'
    | '/reports'
    | '/requests'
    | '/talent'
    | '/employees/$id/edit'
    | '/lifecycle/movements/new'
    | '/lifecycle/offboarding/$id'
    | '/lifecycle/onboarding/$id'
    | '/payroll/runs/$id'
    | '/payroll/runs/new'
    | '/people/positions/$id'
    | '/recruitment/candidates/$id'
    | '/recruitment/requisitions/new'
    | '/relations/cases/$id'
    | '/talent/reviews/$id'
    | '/time/expenses/new'
    | '/time/expenses'
    | '/payroll/runs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/help'
    | '/setup'
    | '/sign-in'
    | '/speak-up'
    | '/attendance/$id'
    | '/attendance/clock'
    | '/attendance/new'
    | '/configuration/business'
    | '/configuration/compliance'
    | '/configuration/organisation'
    | '/configuration/process'
    | '/configuration/roles'
    | '/configuration/technical'
    | '/employees/$id'
    | '/employees/new'
    | '/experience/announcements'
    | '/experience/knowledge'
    | '/experience/letters'
    | '/leave/$id'
    | '/leave/new'
    | '/lifecycle/alumni'
    | '/lifecycle/assets'
    | '/lifecycle/journeys'
    | '/lifecycle/mobility'
    | '/lifecycle/movements'
    | '/lifecycle/offboarding'
    | '/lifecycle/onboarding'
    | '/pay/compensation'
    | '/payroll/exceptions'
    | '/payroll/runs'
    | '/payslips/$id'
    | '/people/data-quality'
    | '/people/documents'
    | '/people/org'
    | '/people/positions'
    | '/people/privacy'
    | '/recruitment/candidates'
    | '/recruitment/offers'
    | '/recruitment/requisitions'
    | '/recruitment/vacancies'
    | '/relations/cases'
    | '/relations/discipline'
    | '/relations/ethics'
    | '/relations/labour'
    | '/relations/safety'
    | '/reports/builder'
    | '/requests/$id'
    | '/requests/new'
    | '/talent/feedback'
    | '/talent/goals'
    | '/talent/learning'
    | '/talent/reviews'
    | '/talent/succession'
    | '/time/schedules'
    | '/time/timesheets'
    | '/time/toil'
    | '/time/travel'
    | '/time/utilisation'
    | '/attendance/'
    | '/configuration/'
    | '/employees/'
    | '/leave/'
    | '/lifecycle/'
    | '/payroll/'
    | '/payslips/'
    | '/recruitment/'
    | '/relations/'
    | '/reports/'
    | '/requests/'
    | '/talent/'
    | '/employees/$id/edit'
    | '/lifecycle/movements/new'
    | '/lifecycle/offboarding/$id'
    | '/lifecycle/onboarding/$id'
    | '/payroll/runs/$id'
    | '/payroll/runs/new'
    | '/people/positions/$id'
    | '/recruitment/candidates/$id'
    | '/recruitment/requisitions/new'
    | '/relations/cases/$id'
    | '/talent/reviews/$id'
    | '/time/expenses/new'
    | '/time/expenses/'
    | '/payroll/runs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  HelpRoute: typeof HelpRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SpeakUpRoute: typeof SpeakUpRoute
  AttendanceIdRoute: typeof AttendanceIdRoute
  AttendanceClockRoute: typeof AttendanceClockRoute
  AttendanceNewRoute: typeof AttendanceNewRoute
  ConfigurationBusinessRoute: typeof ConfigurationBusinessRoute
  ConfigurationComplianceRoute: typeof ConfigurationComplianceRoute
  ConfigurationOrganisationRoute: typeof ConfigurationOrganisationRoute
  ConfigurationProcessRoute: typeof ConfigurationProcessRoute
  ConfigurationRolesRoute: typeof ConfigurationRolesRoute
  ConfigurationTechnicalRoute: typeof ConfigurationTechnicalRoute
  EmployeesIdRoute: typeof EmployeesIdRouteWithChildren
  EmployeesNewRoute: typeof EmployeesNewRoute
  ExperienceAnnouncementsRoute: typeof ExperienceAnnouncementsRoute
  ExperienceKnowledgeRoute: typeof ExperienceKnowledgeRoute
  ExperienceLettersRoute: typeof ExperienceLettersRoute
  LeaveIdRoute: typeof LeaveIdRoute
  LeaveNewRoute: typeof LeaveNewRoute
  LifecycleAlumniRoute: typeof LifecycleAlumniRoute
  LifecycleAssetsRoute: typeof LifecycleAssetsRoute
  LifecycleJourneysRoute: typeof LifecycleJourneysRoute
  LifecycleMobilityRoute: typeof LifecycleMobilityRoute
  LifecycleMovementsRoute: typeof LifecycleMovementsRouteWithChildren
  LifecycleOffboardingRoute: typeof LifecycleOffboardingRouteWithChildren
  LifecycleOnboardingRoute: typeof LifecycleOnboardingRouteWithChildren
  PayCompensationRoute: typeof PayCompensationRoute
  PayrollExceptionsRoute: typeof PayrollExceptionsRoute
  PayrollRunsRoute: typeof PayrollRunsRouteWithChildren
  PayslipsIdRoute: typeof PayslipsIdRoute
  PeopleDataQualityRoute: typeof PeopleDataQualityRoute
  PeopleDocumentsRoute: typeof PeopleDocumentsRoute
  PeopleOrgRoute: typeof PeopleOrgRoute
  PeoplePositionsRoute: typeof PeoplePositionsRouteWithChildren
  PeoplePrivacyRoute: typeof PeoplePrivacyRoute
  RecruitmentCandidatesRoute: typeof RecruitmentCandidatesRouteWithChildren
  RecruitmentOffersRoute: typeof RecruitmentOffersRoute
  RecruitmentRequisitionsRoute: typeof RecruitmentRequisitionsRouteWithChildren
  RecruitmentVacanciesRoute: typeof RecruitmentVacanciesRoute
  RelationsCasesRoute: typeof RelationsCasesRouteWithChildren
  RelationsDisciplineRoute: typeof RelationsDisciplineRoute
  RelationsEthicsRoute: typeof RelationsEthicsRoute
  RelationsLabourRoute: typeof RelationsLabourRoute
  RelationsSafetyRoute: typeof RelationsSafetyRoute
  ReportsBuilderRoute: typeof ReportsBuilderRoute
  RequestsIdRoute: typeof RequestsIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  TalentFeedbackRoute: typeof TalentFeedbackRoute
  TalentGoalsRoute: typeof TalentGoalsRoute
  TalentLearningRoute: typeof TalentLearningRoute
  TalentReviewsRoute: typeof TalentReviewsRouteWithChildren
  TalentSuccessionRoute: typeof TalentSuccessionRoute
  TimeSchedulesRoute: typeof TimeSchedulesRoute
  TimeTimesheetsRoute: typeof TimeTimesheetsRoute
  TimeToilRoute: typeof TimeToilRoute
  TimeTravelRoute: typeof TimeTravelRoute
  TimeUtilisationRoute: typeof TimeUtilisationRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  ConfigurationIndexRoute: typeof ConfigurationIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  LeaveIndexRoute: typeof LeaveIndexRoute
  LifecycleIndexRoute: typeof LifecycleIndexRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
  PayslipsIndexRoute: typeof PayslipsIndexRoute
  RecruitmentIndexRoute: typeof RecruitmentIndexRoute
  RelationsIndexRoute: typeof RelationsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  TalentIndexRoute: typeof TalentIndexRoute
  TimeExpensesNewRoute: typeof TimeExpensesNewRoute
  TimeExpensesIndexRoute: typeof TimeExpensesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speak-up': {
      id: '/speak-up'
      path: '/speak-up'
      fullPath: '/speak-up'
      preLoaderRoute: typeof SpeakUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/$id': {
      id: '/attendance/$id'
      path: '/attendance/$id'
      fullPath: '/attendance/$id'
      preLoaderRoute: typeof AttendanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/clock': {
      id: '/attendance/clock'
      path: '/attendance/clock'
      fullPath: '/attendance/clock'
      preLoaderRoute: typeof AttendanceClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/new': {
      id: '/attendance/new'
      path: '/attendance/new'
      fullPath: '/attendance/new'
      preLoaderRoute: typeof AttendanceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/': {
      id: '/configuration/'
      path: '/configuration'
      fullPath: '/configuration/'
      preLoaderRoute: typeof ConfigurationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/business': {
      id: '/configuration/business'
      path: '/configuration/business'
      fullPath: '/configuration/business'
      preLoaderRoute: typeof ConfigurationBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/compliance': {
      id: '/configuration/compliance'
      path: '/configuration/compliance'
      fullPath: '/configuration/compliance'
      preLoaderRoute: typeof ConfigurationComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/organisation': {
      id: '/configuration/organisation'
      path: '/configuration/organisation'
      fullPath: '/configuration/organisation'
      preLoaderRoute: typeof ConfigurationOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/process': {
      id: '/configuration/process'
      path: '/configuration/process'
      fullPath: '/configuration/process'
      preLoaderRoute: typeof ConfigurationProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/roles': {
      id: '/configuration/roles'
      path: '/configuration/roles'
      fullPath: '/configuration/roles'
      preLoaderRoute: typeof ConfigurationRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/technical': {
      id: '/configuration/technical'
      path: '/configuration/technical'
      fullPath: '/configuration/technical'
      preLoaderRoute: typeof ConfigurationTechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/new': {
      id: '/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/announcements': {
      id: '/experience/announcements'
      path: '/experience/announcements'
      fullPath: '/experience/announcements'
      preLoaderRoute: typeof ExperienceAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/knowledge': {
      id: '/experience/knowledge'
      path: '/experience/knowledge'
      fullPath: '/experience/knowledge'
      preLoaderRoute: typeof ExperienceKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/letters': {
      id: '/experience/letters'
      path: '/experience/letters'
      fullPath: '/experience/letters'
      preLoaderRoute: typeof ExperienceLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/': {
      id: '/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof LeaveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/$id': {
      id: '/leave/$id'
      path: '/leave/$id'
      fullPath: '/leave/$id'
      preLoaderRoute: typeof LeaveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/new': {
      id: '/leave/new'
      path: '/leave/new'
      fullPath: '/leave/new'
      preLoaderRoute: typeof LeaveNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/': {
      id: '/lifecycle/'
      path: '/lifecycle'
      fullPath: '/lifecycle/'
      preLoaderRoute: typeof LifecycleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/alumni': {
      id: '/lifecycle/alumni'
      path: '/lifecycle/alumni'
      fullPath: '/lifecycle/alumni'
      preLoaderRoute: typeof LifecycleAlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/assets': {
      id: '/lifecycle/assets'
      path: '/lifecycle/assets'
      fullPath: '/lifecycle/assets'
      preLoaderRoute: typeof LifecycleAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/journeys': {
      id: '/lifecycle/journeys'
      path: '/lifecycle/journeys'
      fullPath: '/lifecycle/journeys'
      preLoaderRoute: typeof LifecycleJourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/mobility': {
      id: '/lifecycle/mobility'
      path: '/lifecycle/mobility'
      fullPath: '/lifecycle/mobility'
      preLoaderRoute: typeof LifecycleMobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/movements': {
      id: '/lifecycle/movements'
      path: '/lifecycle/movements'
      fullPath: '/lifecycle/movements'
      preLoaderRoute: typeof LifecycleMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/offboarding': {
      id: '/lifecycle/offboarding'
      path: '/lifecycle/offboarding'
      fullPath: '/lifecycle/offboarding'
      preLoaderRoute: typeof LifecycleOffboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/onboarding': {
      id: '/lifecycle/onboarding'
      path: '/lifecycle/onboarding'
      fullPath: '/lifecycle/onboarding'
      preLoaderRoute: typeof LifecycleOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/compensation': {
      id: '/pay/compensation'
      path: '/pay/compensation'
      fullPath: '/pay/compensation'
      preLoaderRoute: typeof PayCompensationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/exceptions': {
      id: '/payroll/exceptions'
      path: '/payroll/exceptions'
      fullPath: '/payroll/exceptions'
      preLoaderRoute: typeof PayrollExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/runs': {
      id: '/payroll/runs'
      path: '/payroll/runs'
      fullPath: '/payroll/runs'
      preLoaderRoute: typeof PayrollRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payslips/': {
      id: '/payslips/'
      path: '/payslips'
      fullPath: '/payslips/'
      preLoaderRoute: typeof PayslipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payslips/$id': {
      id: '/payslips/$id'
      path: '/payslips/$id'
      fullPath: '/payslips/$id'
      preLoaderRoute: typeof PayslipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/data-quality': {
      id: '/people/data-quality'
      path: '/people/data-quality'
      fullPath: '/people/data-quality'
      preLoaderRoute: typeof PeopleDataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/documents': {
      id: '/people/documents'
      path: '/people/documents'
      fullPath: '/people/documents'
      preLoaderRoute: typeof PeopleDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/org': {
      id: '/people/org'
      path: '/people/org'
      fullPath: '/people/org'
      preLoaderRoute: typeof PeopleOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/positions': {
      id: '/people/positions'
      path: '/people/positions'
      fullPath: '/people/positions'
      preLoaderRoute: typeof PeoplePositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/privacy': {
      id: '/people/privacy'
      path: '/people/privacy'
      fullPath: '/people/privacy'
      preLoaderRoute: typeof PeoplePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/': {
      id: '/recruitment/'
      path: '/recruitment'
      fullPath: '/recruitment/'
      preLoaderRoute: typeof RecruitmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/candidates': {
      id: '/recruitment/candidates'
      path: '/recruitment/candidates'
      fullPath: '/recruitment/candidates'
      preLoaderRoute: typeof RecruitmentCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/offers': {
      id: '/recruitment/offers'
      path: '/recruitment/offers'
      fullPath: '/recruitment/offers'
      preLoaderRoute: typeof RecruitmentOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/requisitions': {
      id: '/recruitment/requisitions'
      path: '/recruitment/requisitions'
      fullPath: '/recruitment/requisitions'
      preLoaderRoute: typeof RecruitmentRequisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/vacancies': {
      id: '/recruitment/vacancies'
      path: '/recruitment/vacancies'
      fullPath: '/recruitment/vacancies'
      preLoaderRoute: typeof RecruitmentVacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/': {
      id: '/relations/'
      path: '/relations'
      fullPath: '/relations/'
      preLoaderRoute: typeof RelationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/cases': {
      id: '/relations/cases'
      path: '/relations/cases'
      fullPath: '/relations/cases'
      preLoaderRoute: typeof RelationsCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/discipline': {
      id: '/relations/discipline'
      path: '/relations/discipline'
      fullPath: '/relations/discipline'
      preLoaderRoute: typeof RelationsDisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/ethics': {
      id: '/relations/ethics'
      path: '/relations/ethics'
      fullPath: '/relations/ethics'
      preLoaderRoute: typeof RelationsEthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/labour': {
      id: '/relations/labour'
      path: '/relations/labour'
      fullPath: '/relations/labour'
      preLoaderRoute: typeof RelationsLabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/safety': {
      id: '/relations/safety'
      path: '/relations/safety'
      fullPath: '/relations/safety'
      preLoaderRoute: typeof RelationsSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/builder': {
      id: '/reports/builder'
      path: '/reports/builder'
      fullPath: '/reports/builder'
      preLoaderRoute: typeof ReportsBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/feedback': {
      id: '/talent/feedback'
      path: '/talent/feedback'
      fullPath: '/talent/feedback'
      preLoaderRoute: typeof TalentFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/goals': {
      id: '/talent/goals'
      path: '/talent/goals'
      fullPath: '/talent/goals'
      preLoaderRoute: typeof TalentGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/learning': {
      id: '/talent/learning'
      path: '/talent/learning'
      fullPath: '/talent/learning'
      preLoaderRoute: typeof TalentLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/reviews': {
      id: '/talent/reviews'
      path: '/talent/reviews'
      fullPath: '/talent/reviews'
      preLoaderRoute: typeof TalentReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/succession': {
      id: '/talent/succession'
      path: '/talent/succession'
      fullPath: '/talent/succession'
      preLoaderRoute: typeof TalentSuccessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/schedules': {
      id: '/time/schedules'
      path: '/time/schedules'
      fullPath: '/time/schedules'
      preLoaderRoute: typeof TimeSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/timesheets': {
      id: '/time/timesheets'
      path: '/time/timesheets'
      fullPath: '/time/timesheets'
      preLoaderRoute: typeof TimeTimesheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/toil': {
      id: '/time/toil'
      path: '/time/toil'
      fullPath: '/time/toil'
      preLoaderRoute: typeof TimeToilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/travel': {
      id: '/time/travel'
      path: '/time/travel'
      fullPath: '/time/travel'
      preLoaderRoute: typeof TimeTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/utilisation': {
      id: '/time/utilisation'
      path: '/time/utilisation'
      fullPath: '/time/utilisation'
      preLoaderRoute: typeof TimeUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id/edit': {
      id: '/employees/$id/edit'
      path: '/edit'
      fullPath: '/employees/$id/edit'
      preLoaderRoute: typeof EmployeesIdEditRouteImport
      parentRoute: typeof EmployeesIdRoute
    }
    '/lifecycle/movements/new': {
      id: '/lifecycle/movements/new'
      path: '/new'
      fullPath: '/lifecycle/movements/new'
      preLoaderRoute: typeof LifecycleMovementsNewRouteImport
      parentRoute: typeof LifecycleMovementsRoute
    }
    '/lifecycle/offboarding/$id': {
      id: '/lifecycle/offboarding/$id'
      path: '/$id'
      fullPath: '/lifecycle/offboarding/$id'
      preLoaderRoute: typeof LifecycleOffboardingIdRouteImport
      parentRoute: typeof LifecycleOffboardingRoute
    }
    '/lifecycle/onboarding/$id': {
      id: '/lifecycle/onboarding/$id'
      path: '/$id'
      fullPath: '/lifecycle/onboarding/$id'
      preLoaderRoute: typeof LifecycleOnboardingIdRouteImport
      parentRoute: typeof LifecycleOnboardingRoute
    }
    '/payroll/runs/$id': {
      id: '/payroll/runs/$id'
      path: '/$id'
      fullPath: '/payroll/runs/$id'
      preLoaderRoute: typeof PayrollRunsIdRouteImport
      parentRoute: typeof PayrollRunsRoute
    }
    '/payroll/runs/new': {
      id: '/payroll/runs/new'
      path: '/new'
      fullPath: '/payroll/runs/new'
      preLoaderRoute: typeof PayrollRunsNewRouteImport
      parentRoute: typeof PayrollRunsRoute
    }
    '/people/positions/$id': {
      id: '/people/positions/$id'
      path: '/$id'
      fullPath: '/people/positions/$id'
      preLoaderRoute: typeof PeoplePositionsIdRouteImport
      parentRoute: typeof PeoplePositionsRoute
    }
    '/recruitment/candidates/$id': {
      id: '/recruitment/candidates/$id'
      path: '/$id'
      fullPath: '/recruitment/candidates/$id'
      preLoaderRoute: typeof RecruitmentCandidatesIdRouteImport
      parentRoute: typeof RecruitmentCandidatesRoute
    }
    '/recruitment/requisitions/new': {
      id: '/recruitment/requisitions/new'
      path: '/new'
      fullPath: '/recruitment/requisitions/new'
      preLoaderRoute: typeof RecruitmentRequisitionsNewRouteImport
      parentRoute: typeof RecruitmentRequisitionsRoute
    }
    '/relations/cases/$id': {
      id: '/relations/cases/$id'
      path: '/$id'
      fullPath: '/relations/cases/$id'
      preLoaderRoute: typeof RelationsCasesIdRouteImport
      parentRoute: typeof RelationsCasesRoute
    }
    '/talent/reviews/$id': {
      id: '/talent/reviews/$id'
      path: '/$id'
      fullPath: '/talent/reviews/$id'
      preLoaderRoute: typeof TalentReviewsIdRouteImport
      parentRoute: typeof TalentReviewsRoute
    }
    '/time/expenses/': {
      id: '/time/expenses/'
      path: '/time/expenses'
      fullPath: '/time/expenses/'
      preLoaderRoute: typeof TimeExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/expenses/new': {
      id: '/time/expenses/new'
      path: '/time/expenses/new'
      fullPath: '/time/expenses/new'
      preLoaderRoute: typeof TimeExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/runs/$id/edit': {
      id: '/payroll/runs/$id/edit'
      path: '/edit'
      fullPath: '/payroll/runs/$id/edit'
      preLoaderRoute: typeof PayrollRunsIdEditRouteImport
      parentRoute: typeof PayrollRunsIdRoute
    }
  }
}

interface EmployeesIdRouteChildren {
  EmployeesIdEditRoute: typeof EmployeesIdEditRoute
}

const EmployeesIdRouteChildren: EmployeesIdRouteChildren = {
  EmployeesIdEditRoute: EmployeesIdEditRoute,
}

const EmployeesIdRouteWithChildren = EmployeesIdRoute._addFileChildren(
  EmployeesIdRouteChildren,
)

interface LifecycleMovementsRouteChildren {
  LifecycleMovementsNewRoute: typeof LifecycleMovementsNewRoute
}

const LifecycleMovementsRouteChildren: LifecycleMovementsRouteChildren = {
  LifecycleMovementsNewRoute: LifecycleMovementsNewRoute,
}

const LifecycleMovementsRouteWithChildren =
  LifecycleMovementsRoute._addFileChildren(LifecycleMovementsRouteChildren)

interface LifecycleOffboardingRouteChildren {
  LifecycleOffboardingIdRoute: typeof LifecycleOffboardingIdRoute
}

const LifecycleOffboardingRouteChildren: LifecycleOffboardingRouteChildren = {
  LifecycleOffboardingIdRoute: LifecycleOffboardingIdRoute,
}

const LifecycleOffboardingRouteWithChildren =
  LifecycleOffboardingRoute._addFileChildren(LifecycleOffboardingRouteChildren)

interface LifecycleOnboardingRouteChildren {
  LifecycleOnboardingIdRoute: typeof LifecycleOnboardingIdRoute
}

const LifecycleOnboardingRouteChildren: LifecycleOnboardingRouteChildren = {
  LifecycleOnboardingIdRoute: LifecycleOnboardingIdRoute,
}

const LifecycleOnboardingRouteWithChildren =
  LifecycleOnboardingRoute._addFileChildren(LifecycleOnboardingRouteChildren)

interface PayrollRunsIdRouteChildren {
  PayrollRunsIdEditRoute: typeof PayrollRunsIdEditRoute
}

const PayrollRunsIdRouteChildren: PayrollRunsIdRouteChildren = {
  PayrollRunsIdEditRoute: PayrollRunsIdEditRoute,
}

const PayrollRunsIdRouteWithChildren = PayrollRunsIdRoute._addFileChildren(
  PayrollRunsIdRouteChildren,
)

interface PayrollRunsRouteChildren {
  PayrollRunsIdRoute: typeof PayrollRunsIdRouteWithChildren
  PayrollRunsNewRoute: typeof PayrollRunsNewRoute
}

const PayrollRunsRouteChildren: PayrollRunsRouteChildren = {
  PayrollRunsIdRoute: PayrollRunsIdRouteWithChildren,
  PayrollRunsNewRoute: PayrollRunsNewRoute,
}

const PayrollRunsRouteWithChildren = PayrollRunsRoute._addFileChildren(
  PayrollRunsRouteChildren,
)

interface PeoplePositionsRouteChildren {
  PeoplePositionsIdRoute: typeof PeoplePositionsIdRoute
}

const PeoplePositionsRouteChildren: PeoplePositionsRouteChildren = {
  PeoplePositionsIdRoute: PeoplePositionsIdRoute,
}

const PeoplePositionsRouteWithChildren = PeoplePositionsRoute._addFileChildren(
  PeoplePositionsRouteChildren,
)

interface RecruitmentCandidatesRouteChildren {
  RecruitmentCandidatesIdRoute: typeof RecruitmentCandidatesIdRoute
}

const RecruitmentCandidatesRouteChildren: RecruitmentCandidatesRouteChildren = {
  RecruitmentCandidatesIdRoute: RecruitmentCandidatesIdRoute,
}

const RecruitmentCandidatesRouteWithChildren =
  RecruitmentCandidatesRoute._addFileChildren(
    RecruitmentCandidatesRouteChildren,
  )

interface RecruitmentRequisitionsRouteChildren {
  RecruitmentRequisitionsNewRoute: typeof RecruitmentRequisitionsNewRoute
}

const RecruitmentRequisitionsRouteChildren: RecruitmentRequisitionsRouteChildren =
  {
    RecruitmentRequisitionsNewRoute: RecruitmentRequisitionsNewRoute,
  }

const RecruitmentRequisitionsRouteWithChildren =
  RecruitmentRequisitionsRoute._addFileChildren(
    RecruitmentRequisitionsRouteChildren,
  )

interface RelationsCasesRouteChildren {
  RelationsCasesIdRoute: typeof RelationsCasesIdRoute
}

const RelationsCasesRouteChildren: RelationsCasesRouteChildren = {
  RelationsCasesIdRoute: RelationsCasesIdRoute,
}

const RelationsCasesRouteWithChildren = RelationsCasesRoute._addFileChildren(
  RelationsCasesRouteChildren,
)

interface TalentReviewsRouteChildren {
  TalentReviewsIdRoute: typeof TalentReviewsIdRoute
}

const TalentReviewsRouteChildren: TalentReviewsRouteChildren = {
  TalentReviewsIdRoute: TalentReviewsIdRoute,
}

const TalentReviewsRouteWithChildren = TalentReviewsRoute._addFileChildren(
  TalentReviewsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  HelpRoute: HelpRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SpeakUpRoute: SpeakUpRoute,
  AttendanceIdRoute: AttendanceIdRoute,
  AttendanceClockRoute: AttendanceClockRoute,
  AttendanceNewRoute: AttendanceNewRoute,
  ConfigurationBusinessRoute: ConfigurationBusinessRoute,
  ConfigurationComplianceRoute: ConfigurationComplianceRoute,
  ConfigurationOrganisationRoute: ConfigurationOrganisationRoute,
  ConfigurationProcessRoute: ConfigurationProcessRoute,
  ConfigurationRolesRoute: ConfigurationRolesRoute,
  ConfigurationTechnicalRoute: ConfigurationTechnicalRoute,
  EmployeesIdRoute: EmployeesIdRouteWithChildren,
  EmployeesNewRoute: EmployeesNewRoute,
  ExperienceAnnouncementsRoute: ExperienceAnnouncementsRoute,
  ExperienceKnowledgeRoute: ExperienceKnowledgeRoute,
  ExperienceLettersRoute: ExperienceLettersRoute,
  LeaveIdRoute: LeaveIdRoute,
  LeaveNewRoute: LeaveNewRoute,
  LifecycleAlumniRoute: LifecycleAlumniRoute,
  LifecycleAssetsRoute: LifecycleAssetsRoute,
  LifecycleJourneysRoute: LifecycleJourneysRoute,
  LifecycleMobilityRoute: LifecycleMobilityRoute,
  LifecycleMovementsRoute: LifecycleMovementsRouteWithChildren,
  LifecycleOffboardingRoute: LifecycleOffboardingRouteWithChildren,
  LifecycleOnboardingRoute: LifecycleOnboardingRouteWithChildren,
  PayCompensationRoute: PayCompensationRoute,
  PayrollExceptionsRoute: PayrollExceptionsRoute,
  PayrollRunsRoute: PayrollRunsRouteWithChildren,
  PayslipsIdRoute: PayslipsIdRoute,
  PeopleDataQualityRoute: PeopleDataQualityRoute,
  PeopleDocumentsRoute: PeopleDocumentsRoute,
  PeopleOrgRoute: PeopleOrgRoute,
  PeoplePositionsRoute: PeoplePositionsRouteWithChildren,
  PeoplePrivacyRoute: PeoplePrivacyRoute,
  RecruitmentCandidatesRoute: RecruitmentCandidatesRouteWithChildren,
  RecruitmentOffersRoute: RecruitmentOffersRoute,
  RecruitmentRequisitionsRoute: RecruitmentRequisitionsRouteWithChildren,
  RecruitmentVacanciesRoute: RecruitmentVacanciesRoute,
  RelationsCasesRoute: RelationsCasesRouteWithChildren,
  RelationsDisciplineRoute: RelationsDisciplineRoute,
  RelationsEthicsRoute: RelationsEthicsRoute,
  RelationsLabourRoute: RelationsLabourRoute,
  RelationsSafetyRoute: RelationsSafetyRoute,
  ReportsBuilderRoute: ReportsBuilderRoute,
  RequestsIdRoute: RequestsIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  TalentFeedbackRoute: TalentFeedbackRoute,
  TalentGoalsRoute: TalentGoalsRoute,
  TalentLearningRoute: TalentLearningRoute,
  TalentReviewsRoute: TalentReviewsRouteWithChildren,
  TalentSuccessionRoute: TalentSuccessionRoute,
  TimeSchedulesRoute: TimeSchedulesRoute,
  TimeTimesheetsRoute: TimeTimesheetsRoute,
  TimeToilRoute: TimeToilRoute,
  TimeTravelRoute: TimeTravelRoute,
  TimeUtilisationRoute: TimeUtilisationRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  ConfigurationIndexRoute: ConfigurationIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  LeaveIndexRoute: LeaveIndexRoute,
  LifecycleIndexRoute: LifecycleIndexRoute,
  PayrollIndexRoute: PayrollIndexRoute,
  PayslipsIndexRoute: PayslipsIndexRoute,
  RecruitmentIndexRoute: RecruitmentIndexRoute,
  RelationsIndexRoute: RelationsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  TalentIndexRoute: TalentIndexRoute,
  TimeExpensesNewRoute: TimeExpensesNewRoute,
  TimeExpensesIndexRoute: TimeExpensesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
