import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Clock3, Download, Eye, Filter, MoreHorizontal, Plus, Search, ShieldCheck, TimerReset, UserCheck, UserRound, UserX } from "lucide-react";
import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AppShell } from "@/platform/components/AppShell";
import { AuthGate } from "@/platform/components/AuthGate";
import { PageHeader } from "@/platform/components/PageHeader";
import { useMock } from "@/platform/use-mock";
import { expensesApi } from "@/mock/expenses";
import type { Timesheet } from "@/mock/expenses";
import { feedback } from "@/platform/feedback";

export const Route = createFileRoute("/hrm/time/timesheets")({
  head: () => ({
    meta: [
      { title: "Timesheet summary — New World Cargo HRM" },
      { name: "description", content: "Track attendance hours in one focused timesheet workspace." },
    ],
  }),
  component: TimesheetsPage,
});

type StatusFilter = "all" | "active" | "attention" | "leave";
type RowStatus = "Active" | "On-leave" | "Incomplete" | "Late";
type DrawerView = "detail" | "overtime" | "payroll";
type AttendanceRow = { id: string; employee: string; initials: string; date: string; clockIn: string; clockOut: string; worked: string; overtime: string; multiplier?: string; shift: string; status: RowStatus; tag?: "Overtime" | "Incomplete" | "Late" };

const PREVIEW_ROWS: AttendanceRow[] = [
  { id: "p-1", employee: "Bin Amal", initials: "BA", date: "4 Nov 2024", clockIn: "10:00 AM", clockOut: "7:50 PM", worked: "09h 50m", overtime: "1h 50m", multiplier: "1.5x", shift: "Normal shift", status: "Active", tag: "Overtime" },
  { id: "p-2", employee: "Logan Wolves", initials: "LW", date: "4 Nov 2024", clockIn: "—", clockOut: "—", worked: "—", overtime: "—", shift: "Normal shift", status: "On-leave" },
  { id: "p-3", employee: "Wanda Fury", initials: "WF", date: "4 Nov 2024", clockIn: "10:00 AM", clockOut: "4:50 PM", worked: "06h 50m", overtime: "—", shift: "Normal shift", status: "Incomplete", tag: "Incomplete" },
  { id: "p-4", employee: "Saber Trot", initials: "ST", date: "4 Nov 2024", clockIn: "10:00 AM", clockOut: "6:00 PM", worked: "09h 00m", overtime: "—", shift: "Normal shift", status: "Active" },
  { id: "p-5", employee: "Ben Unclor", initials: "BU", date: "4 Nov 2024", clockIn: "10:00 AM", clockOut: "6:00 PM", worked: "09h 00m", overtime: "—", shift: "Normal shift", status: "Active" },
  { id: "p-6", employee: "Shaun Chi", initials: "SC", date: "4 Nov 2024", clockIn: "11:00 AM", clockOut: "7:00 PM", worked: "09h 00m", overtime: "—", shift: "Normal shift", status: "Late", tag: "Late" },
  { id: "p-7", employee: "Peter Parkson", initials: "PP", date: "4 Nov 2024", clockIn: "10:00 AM", clockOut: "6:00 PM", worked: "09h 00m", overtime: "—", shift: "Normal shift", status: "Active" },
];

function TimesheetsPage() {
  const state = useMock(() => expensesApi.timesheets());
  const [previewMode, setPreviewMode] = useState(false);
  const [dateOffset, setDateOffset] = useState(0);
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [addOpen, setAddOpen] = useState(false);
  const [selectedRow, setSelectedRow] = useState<AttendanceRow | null>(null);
  const [drawerView, setDrawerView] = useState<DrawerView>("detail");
  const [decisionNote, setDecisionNote] = useState("");
  const [decision, setDecision] = useState<"approved" | "rejected" | null>(null);
  const date = useMemo(() => new Date(Date.UTC(2024, 10, 4 + dateOffset)), [dateOffset]);
  const dateLabel = date.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });

  const realRows = useMemo(() => adaptRealTimesheets((state.data ?? []) as Timesheet[]), [state.data]);
  const rows = previewMode ? PREVIEW_ROWS : realRows;
  const visibleRows = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return rows.filter((row) => {
      const matchesQuery = !needle || `${row.employee} ${row.shift} ${row.status} ${row.tag ?? ""}`.toLowerCase().includes(needle);
      const matchesFilter = statusFilter === "all" || (statusFilter === "active" && row.status === "Active") || (statusFilter === "attention" && (row.status === "Incomplete" || row.status === "Late" || row.tag === "Overtime")) || (statusFilter === "leave" && row.status === "On-leave");
      return matchesQuery && matchesFilter;
    });
  }, [query, rows, statusFilter]);

  const kpis = useMemo(() => ({
    present: rows.filter((row) => row.status === "Active").length,
    late: rows.filter((row) => row.tag === "Late").length,
    leave: rows.filter((row) => row.status === "On-leave").length,
    overtime: rows.filter((row) => row.tag === "Overtime").length,
  }), [rows]);

  function openDetail(row: AttendanceRow) { setSelectedRow(row); setDrawerView("detail"); setDecision(null); setDecisionNote(""); }
  function closeDrawer() { setSelectedRow(null); setDrawerView("detail"); setDecision(null); setDecisionNote(""); }
  function submitDecision(nextDecision: "approved" | "rejected") {
    if (nextDecision === "rejected" && !decisionNote.trim()) {
      feedback.note("Decision note required", "Explain why this overtime should be rejected before continuing.");
      return;
    }
    setDecision(nextDecision);
    setDrawerView("payroll");
    feedback.note(nextDecision === "approved" ? "Overtime approved in preview" : "Overtime rejected in preview", "This preview decision is not saved until the live attendance service is connected.");
  }

  return <AuthGate><AppShell><PageHeader eyebrow="Time and leave / attendance" title="Timesheet summary" description="Track and manage attendance hours effortlessly." meta={<Badge variant="outline" className={`gap-1.5 ${previewMode ? "border-warning/50 bg-warning-soft text-warning-foreground" : "border-info/30 bg-info-soft text-info-foreground"}`}><Eye className="size-3" aria-hidden />{previewMode ? "Sample UI preview · not saved" : "Real attendance only · preview off"}</Badge>} primaryAction={<Button onClick={() => setAddOpen(true)} className="gap-2"><Plus className="size-4" aria-hidden />Add attendance</Button>} />
    <div className="space-y-4" data-testid="timesheets-page">
      <div className="flex flex-col gap-3 border-b pb-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-1"><Button variant="outline" size="icon" aria-label="Previous day" onClick={() => setDateOffset((value) => value - 1)}><ChevronLeft className="size-4" aria-hidden /></Button><Button variant="outline" size="icon" aria-label="Next day" onClick={() => setDateOffset((value) => value + 1)}><ChevronRight className="size-4" aria-hidden /></Button><Button variant="ghost" size="sm" onClick={() => setDateOffset(0)}>Today</Button><Button variant="outline" className="ml-1 gap-2" onClick={() => feedback.note("Date scope", "Choose a day when the live attendance period selector is connected.")}><CalendarDays className="size-4" aria-hidden />{dateLabel}<ChevronDown className="size-3.5" aria-hidden /></Button></div><div className="flex flex-wrap items-center gap-2"><Button variant="outline" className="gap-2" onClick={() => feedback.note("Download prepared", "The selected attendance timesheet will be exported when the live service is connected.")}><Download className="size-4" aria-hidden />Download</Button><Button variant={previewMode ? "default" : "outline"} className="gap-2" onClick={() => setPreviewMode((value) => !value)}><Eye className="size-4" aria-hidden />{previewMode ? "Hide preview" : "Preview sample"}</Button></div></div>
      {previewMode ? <div className="flex flex-col gap-2 rounded-lg border border-warning/50 bg-warning-soft/35 px-4 py-3 text-sm sm:flex-row sm:items-center sm:justify-between"><span><strong>UI preview mode.</strong> Sample attendance rows are shown only to review this layout. They are not from PostgreSQL and nothing is saved.</span><Button variant="ghost" size="sm" onClick={() => setPreviewMode(false)}>Return to real data</Button></div> : null}
      {addOpen ? <Card className="border-primary/30 bg-primary-soft/20 shadow-none"><CardContent className="p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold">Add attendance</p><p className="text-sm text-muted-foreground">Record a clock-in and clock-out pair for an employee.</p></div><Button variant="ghost" size="sm" onClick={() => setAddOpen(false)}>Close</Button></div><div className="mt-3 grid gap-3 md:grid-cols-4"><Input placeholder="Employee" aria-label="Employee" /><Input type="date" aria-label="Attendance date" /><Input type="time" aria-label="Clock-in time" /><Input type="time" aria-label="Clock-out time" /></div><p className="mt-3 text-xs text-muted-foreground">Frontend-only preview: no production attendance record will be created.</p></CardContent></Card> : null}
      <section className="grid grid-cols-2 gap-3 border-y py-4 md:grid-cols-4" aria-label="Attendance summary"><Kpi label="Present" value={kpis.present} detail={previewMode ? "+7.1% vs prev" : "Live records only"} icon={UserCheck} tone="success" /><Kpi label="Late clock-in" value={kpis.late} detail={previewMode ? "+7.1% vs prev" : "Live records only"} icon={Clock3} tone="warning" /><Kpi label="On-leave" value={kpis.leave} detail={previewMode ? "+7.1% vs prev" : "Live records only"} icon={UserX} tone="neutral" /><Kpi label="Overtime" value={kpis.overtime} detail={previewMode ? "+7.1% vs prev" : "Needs review"} icon={TimerReset} tone="gold" /></section>
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="relative w-full md:max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search employees..." className="pl-9" aria-label="Search employees" /></div><div className="flex flex-wrap items-center gap-2"><Select value={statusFilter} onValueChange={(value) => setStatusFilter(value as StatusFilter)}><SelectTrigger className="w-36 gap-2" aria-label="Filter status"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All status</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="attention">Needs attention</SelectItem><SelectItem value="leave">On-leave</SelectItem></SelectContent></Select><Button variant="outline" className="gap-2" onClick={() => feedback.note("Filters ready", "Additional branch and period filters will use the same toolbar when connected.")}><Filter className="size-4" aria-hidden />Filter</Button><Button variant="outline" className="gap-2" onClick={() => feedback.note("Export prepared", "Export will respect the selected date, status and search filters.")}><Download className="size-4" aria-hidden />Export</Button></div></div>
      <Card className="overflow-hidden shadow-sm"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><caption className="sr-only">Attendance timesheet summary for {dateLabel}</caption><thead className="bg-surface-muted/70 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3 font-medium"><span className="inline-flex items-center gap-2"><input type="checkbox" aria-label="Select all attendance rows" className="size-4 rounded border-border" />Employee <ChevronDown className="size-3" aria-hidden /></span></th><th className="px-4 py-3 font-medium">Clock-in &amp; out</th><th className="px-4 py-3 font-medium">Overtime</th><th className="px-4 py-3 font-medium">Shift</th><th className="px-4 py-3 font-medium">Status</th><th className="w-12 px-4 py-3" /></tr></thead><tbody className="divide-y">{visibleRows.length ? visibleRows.map((row) => <AttendanceTableRow key={row.id} row={row} onOpen={() => openDetail(row)} />) : <tr><td colSpan={6} className="px-6 py-16 text-center"><UserRound className="mx-auto size-7 text-muted-foreground" aria-hidden /><p className="mt-3 font-medium">{previewMode ? "No sample rows match this filter" : "No live attendance rows"}</p><p className="mt-1 text-sm text-muted-foreground">{previewMode ? "Try All status or clear the search." : "Connect the live attendance/timesheet service before showing employee time."}</p></td></tr>}</tbody></table></div><div className="flex flex-col gap-3 border-t px-4 py-3 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span>Page 1 of {previewMode ? "1" : "—"}</span><div className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label="Previous page" disabled><ChevronLeft className="size-4" aria-hidden /></Button><Button variant="outline" size="sm">1</Button><Button variant="ghost" size="icon" aria-label="Next page" disabled><ChevronRight className="size-4" aria-hidden /></Button><Select defaultValue="7"><SelectTrigger className="ml-2 h-8 w-20" aria-label="Rows per page"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="7">7 / page</SelectItem><SelectItem value="25">25 / page</SelectItem><SelectItem value="50">50 / page</SelectItem></SelectContent></Select></div></div></CardContent></Card>
    </div>
    <AttendanceDrawer row={selectedRow} view={drawerView} decision={decision} decisionNote={decisionNote} onDecisionNoteChange={setDecisionNote} onViewChange={setDrawerView} onClose={closeDrawer} onDecision={submitDecision} previewMode={previewMode} />
  </AppShell></AuthGate>;
}

function Kpi({ label, value, detail, icon: Icon, tone }: { label: string; value: number; detail: string; icon: typeof UserCheck; tone: "success" | "warning" | "neutral" | "gold" }) { const classes = { success: "bg-success-soft text-success-foreground", warning: "bg-warning-soft text-warning-foreground", neutral: "bg-secondary text-secondary-foreground", gold: "bg-warning-soft text-warning-foreground" }; return <div className="flex items-center gap-3 px-1 sm:px-3"><span className={`flex size-9 shrink-0 items-center justify-center rounded-lg ${classes[tone]}`}><Icon className="size-4" aria-hidden /></span><div className="min-w-0"><p className="text-sm text-muted-foreground">{label}</p><p className="text-xl font-semibold tabular">{value.toLocaleString()}</p><p className="text-[11px] text-success-foreground">{detail}</p></div></div>; }

function AttendanceTableRow({ row, onOpen }: { row: AttendanceRow; onOpen: () => void }) { const statusClass: Record<RowStatus, string> = { Active: "border-success/30 bg-success-soft text-success-foreground", "On-leave": "border-border bg-muted text-muted-foreground", Incomplete: "border-danger/30 bg-danger-soft text-danger", Late: "border-warning/40 bg-warning-soft text-warning-foreground" }; const tagClass = row.tag === "Overtime" ? "border-warning/40 bg-warning-soft text-warning-foreground" : row.tag === "Incomplete" ? "border-danger/30 bg-danger-soft text-danger" : "border-warning/40 bg-warning-soft text-warning-foreground"; return <tr className="group cursor-pointer hover:bg-surface-muted/40" onClick={onOpen}><td className="px-4 py-3.5"><div className="flex items-center gap-3"><input type="checkbox" aria-label={`Select ${row.employee}`} className="size-4 rounded border-border" onClick={(event) => event.stopPropagation()} /><span className="flex size-8 items-center justify-center rounded-full bg-secondary text-xs font-semibold text-secondary-foreground">{row.initials}</span><span className="font-medium">{row.employee}</span></div></td><td className="px-4 py-3.5"><div className="flex items-center gap-2 text-sm tabular"><span>{row.clockIn}</span><span className="text-muted-foreground">···</span><span>{row.worked}</span><span className="text-muted-foreground">···</span><span>{row.clockOut}</span></div></td><td className="px-4 py-3.5 font-medium tabular">{row.overtime}</td><td className="px-4 py-3.5 text-muted-foreground">{row.shift}</td><td className="px-4 py-3.5"><div className="flex flex-wrap gap-1.5"><Badge variant="outline" className={statusClass[row.status]}>{row.status}</Badge>{row.tag ? <Badge variant="outline" className={tagClass}>{row.tag}</Badge> : null}</div></td><td className="px-4 py-3.5 text-right"><Button variant="ghost" size="icon" aria-label={`Open attendance details for ${row.employee}`} onClick={(event) => { event.stopPropagation(); onOpen(); }}><MoreHorizontal className="size-4" aria-hidden /></Button></td></tr>; }

function AttendanceDrawer({ row, view, decision, decisionNote, onDecisionNoteChange, onViewChange, onClose, onDecision, previewMode }: { row: AttendanceRow | null; view: DrawerView; decision: "approved" | "rejected" | null; decisionNote: string; onDecisionNoteChange: (value: string) => void; onViewChange: (view: DrawerView) => void; onClose: () => void; onDecision: (decision: "approved" | "rejected") => void; previewMode: boolean }) { return <Dialog open={Boolean(row)} onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto">{row ? view === "detail" ? <DetailView row={row} onClose={onClose} onReview={() => onViewChange("overtime")} /> : view === "overtime" ? <OvertimeView row={row} decisionNote={decisionNote} onDecisionNoteChange={onDecisionNoteChange} onBack={() => onViewChange("detail")} onDecision={onDecision} previewMode={previewMode} /> : <PayrollHandoffView row={row} decision={decision} decisionNote={decisionNote} onBack={() => onViewChange("overtime")} onClose={onClose} previewMode={previewMode} /> : null}</DialogContent></Dialog>; }

function DetailView({ row, onClose, onReview }: { row: AttendanceRow; onClose: () => void; onReview: () => void }) { return <><DialogHeader><DialogTitle>{row.employee}</DialogTitle><DialogDescription>{row.date} · Attendance record</DialogDescription></DialogHeader><div className="space-y-5"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{row.status}</Badge>{row.tag ? <Badge variant="outline" className="border-warning/40 bg-warning-soft text-warning-foreground">{row.tag}</Badge> : null}</div><div className="grid gap-3 sm:grid-cols-4"><Metric label="Clock-in" value={row.clockIn} /><Metric label="Clock-out" value={row.clockOut} /><Metric label="Worked" value={row.worked} /><Metric label="Overtime" value={row.overtime} /></div><div className="grid gap-3 rounded-lg border bg-surface-muted/40 p-4 sm:grid-cols-2"><Info label="Shift" value={row.shift} /><Info label="Source" value="Attendance record" /><Info label="Correction state" value={row.status === "Incomplete" ? "Needs correction" : "No correction raised" } /><Info label="Payroll state" value={row.tag === "Overtime" ? "Awaiting overtime review" : "Not applicable"} /></div>{row.tag === "Overtime" ? <div className="rounded-lg border border-warning/40 bg-warning-soft/30 p-4"><div className="flex items-start gap-3"><TimerReset className="mt-0.5 size-5 text-warning-foreground" aria-hidden /><div><p className="font-semibold">Overtime needs a decision</p><p className="mt-1 text-sm text-muted-foreground">Review the attendance evidence and approve or reject the derived overtime before it can move to payroll.</p></div></div></div> : null}</div><DialogFooter className="gap-2 sm:justify-between"><Button variant="outline" onClick={onClose}>Close</Button>{row.tag === "Overtime" ? <Button onClick={onReview} className="gap-2"><ShieldCheck className="size-4" aria-hidden />Review overtime</Button> : null}</DialogFooter></>; }

function OvertimeView({ row, decisionNote, onDecisionNoteChange, onBack, onDecision, previewMode }: { row: AttendanceRow; decisionNote: string; onDecisionNoteChange: (value: string) => void; onBack: () => void; onDecision: (decision: "approved" | "rejected") => void; previewMode: boolean }) { return <><DialogHeader><DialogTitle>Review overtime</DialogTitle><DialogDescription>{row.employee} · {row.date}</DialogDescription></DialogHeader><div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Overtime" value={row.overtime} /><Metric label="Multiplier" value={row.multiplier ?? "—"} /><Metric label="Source" value="Attendance" /></div><div className="rounded-lg border bg-surface-muted/40 p-4"><p className="text-sm font-semibold">Attendance evidence</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><Info label="Clock-in" value={row.clockIn} /><Info label="Clock-out" value={row.clockOut} /><Info label="Worked" value={row.worked} /></div><p className="mt-3 text-xs text-muted-foreground">The overtime decision must be based on the recorded attendance and assigned shift. The live service will show the exact rule calculation here.</p></div><div className="space-y-2"><Label htmlFor="overtime-decision-note">Decision note {"(required for rejection)"}</Label><Textarea id="overtime-decision-note" value={decisionNote} onChange={(event) => onDecisionNoteChange(event.target.value)} placeholder="Explain the overtime decision..." /><p className="text-xs text-muted-foreground">Preview only: this note is not saved.</p></div></div><DialogFooter className="gap-2 sm:justify-between"><Button variant="outline" onClick={onBack}>Back to attendance</Button><div className="flex gap-2"><Button variant="outline" className="border-danger/40 text-danger hover:bg-danger-soft" onClick={() => onDecision("rejected")}>Reject</Button><Button onClick={() => onDecision("approved")} className="gap-2"><ShieldCheck className="size-4" aria-hidden />Approve overtime</Button></div></DialogFooter></>; }

function PayrollHandoffView({ row, decision, decisionNote, onBack, onClose, previewMode }: { row: AttendanceRow; decision: "approved" | "rejected" | null; decisionNote: string; onBack: () => void; onClose: () => void; previewMode: boolean }) { const approved = decision === "approved"; return <><DialogHeader><DialogTitle>{approved ? "Approved for payroll" : "Overtime rejected"}</DialogTitle><DialogDescription>{row.employee} · {row.date}</DialogDescription></DialogHeader><div className="space-y-5"><div className={`rounded-lg border p-4 ${approved ? "border-success/30 bg-success-soft/30" : "border-danger/30 bg-danger-soft/30"}`}><div className="flex items-start gap-3"><ShieldCheck className={`mt-0.5 size-5 ${approved ? "text-success-foreground" : "text-danger"}`} aria-hidden /><div><p className="font-semibold">{approved ? "One approved overtime item is ready for payroll" : "This overtime will not enter payroll"}</p><p className="mt-1 text-sm text-muted-foreground">{previewMode ? "Preview state only. No attendance or payroll record has been changed." : "Live payroll linkage will appear here after the service is connected."}</p></div></div></div><div className="grid gap-3 rounded-lg border bg-surface-muted/40 p-4 sm:grid-cols-2"><Info label="Employee" value={row.employee} /><Info label="Overtime" value={row.overtime} /><Info label="Payroll run" value={approved ? "Pending live payroll period" : "Not allocated"} /><Info label="Decision note" value={decisionNote || "No note provided"} /></div></div><DialogFooter className="gap-2 sm:justify-between"><Button variant="outline" onClick={onBack}>Back to review</Button><Button onClick={onClose}>{approved ? "Close" : "Done"}</Button></DialogFooter></>; }

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold tabular">{value}</p></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>; }

function adaptRealTimesheets(timesheets: Timesheet[]): AttendanceRow[] { return timesheets.flatMap((timesheet) => { const initials = timesheet.employee.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase(); const totalHours = timesheet.rows.reduce((sum, row) => sum + row.hours.reduce((subtotal, value) => subtotal + value, 0), 0); const overtimeHours = timesheet.rows.reduce((sum, row) => sum + row.overtime.reduce((subtotal, value) => subtotal + value, 0), 0); const formatHours = (value: number) => `${value.toFixed(2)} h`; return [{ id: timesheet.id, employee: timesheet.employee, initials, date: timesheet.weekStarting, clockIn: "—", clockOut: "—", worked: formatHours(totalHours + overtimeHours), overtime: overtimeHours ? formatHours(overtimeHours) : "—", shift: "Assigned shift", status: overtimeHours ? "Late" : "Active", tag: overtimeHours ? "Overtime" : undefined } satisfies AttendanceRow]; }); }
